language: node_js
sudo: false
services:
  - docker
  - mongodb
env:
  global:
    - MONGODB_VERSION=2.6.10
before_install:
  - mongo admin --eval 'db.createUser({user:"admin",pwd:"admin",roles:["readWrite"]});'
node_js:
  - 10
  - 9
  - 8
  - 7
install:
  - npm install
script:
  - npm test
